

伯乐在线
http://hao.jobbole.com/?catid=67

learn-angular
http://www.learn-angular.org/

slideout
https://mango.github.io/slideout/

awesome-resources
https://github.com/gottaBoy/awesome-resources

html5
https://platform.html5.org/

angularjs
https://docs.angularjs.org/guide

bower使用方法
https://www.codementor.io/bower/tutorial/beginner-tutorial-getting-started-bower-package-manager

phonegap100
http://bbs.phonegap100.com/thread-2047-1-1.html

http://bbs.phonegap100.com/thread-2263-1-1.html

npm install -g browser-sync
https://www.browsersync.io/


